// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMmfhFN8goxb3tU2e0C6A-tU-ipyxesdo',
    appId: '1:210649767795:web:c01a84f4ddcf2d7fc16f06',
    messagingSenderId: '210649767795',
    projectId: 'fitplanner-c6d3d',
    authDomain: 'fitplanner-c6d3d.firebaseapp.com',
    storageBucket: 'fitplanner-c6d3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnR9tban9Qoe_lSro5ziwYRiLZCxMfgV8',
    appId: '1:210649767795:android:6b6c3d36cc21aec6c16f06',
    messagingSenderId: '210649767795',
    projectId: 'fitplanner-c6d3d',
    storageBucket: 'fitplanner-c6d3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5Kidy8VJHERlgdLUZYURZPodkEoA6iU',
    appId: '1:210649767795:ios:28cc7f6c20b6bb7ec16f06',
    messagingSenderId: '210649767795',
    projectId: 'fitplanner-c6d3d',
    storageBucket: 'fitplanner-c6d3d.firebasestorage.app',
    iosClientId: '210649767795-upihdecmojsvikuj0jq6tpmprpsbjckn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH5Kidy8VJHERlgdLUZYURZPodkEoA6iU',
    appId: '1:210649767795:ios:28cc7f6c20b6bb7ec16f06',
    messagingSenderId: '210649767795',
    projectId: 'fitplanner-c6d3d',
    storageBucket: 'fitplanner-c6d3d.firebasestorage.app',
    iosClientId: '210649767795-upihdecmojsvikuj0jq6tpmprpsbjckn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMmfhFN8goxb3tU2e0C6A-tU-ipyxesdo',
    appId: '1:210649767795:web:e6b1df3495fc4abcc16f06',
    messagingSenderId: '210649767795',
    projectId: 'fitplanner-c6d3d',
    authDomain: 'fitplanner-c6d3d.firebaseapp.com',
    storageBucket: 'fitplanner-c6d3d.firebasestorage.app',
  );
}
